### ISSUE TITLE
segmentation fault on terminal resize

### ISSUE THREAD

**Issue by 532910** [patroclos/PAmix#43]
pamix from  debian sid, 1.6~git20180112.ea4ab3b-3

**Comment by patroclos** [comment]
does this always happen?
also, could you provide a coredump for this issue?

**Comment by 532910** [comment]
Not always but very frequent, ie it crashes within 1-2 seconds of aggressively resizing the terminal window with the mouse in both directions.

I've tried to catchsegv but it shows nothing, how should I get coredump?

**Comment by patroclos** [comment]
I've tried doing what you described with the NixOS distribution of PAmix yesterday and indeed after some aggressive resizing the terminal just cleared and nothing happened, the program however didn't terminate, as I had to press Ctrl+C to regain control and the exit code didn't indicate a segfault.

Since catchsegv didn't catch anything I'd assume it's the same for you and there is a deadlock somewhere in the resizing code.

If however you did get a segfault, then you could check out the [ulimit -c unlimited](https://wiki.archlinux.org/index.php/Core_dump#Using_ulimit) command.

I'm gonna take a closer look at this in the next couple of days, thx for your patience ;)

**Comment by 532910** [comment]
1. in my case I don't need to press ctrl-c, it returns to the terminal
2. I need to resize terminal in both directions
3. core dumped, size 316M, zstd compressed 378K, I'll send it to your mail.

**Comment by patroclos** [comment]
[this line](https://github.com/patroclos/PAmix/blob/3a59db5759aa498374afe190aef90e431fd204a7/src/pamix.cpp#L104) seems to be the issue.
I'll probably need to synchronize this somewhere, maybe even in the main redraw signal stream.

**Comment by patroclos** [comment]
@532910 On my system [this branch](https://github.com/patroclos/PAmix/tree/bug-resize-segfault) seems to have eliminated the issue, could you confirm that this also works for you?

**Comment by 532910** [comment]
Yes, I can't segfault it more. (: Moreover #44 is also fixed in bug-resize-segfault branch.

**Comment by patroclos** [comment]
So this issue is related to the ncurses resize extension that automagically registers a SIGWINCH handler and injects a KEY_RESIZE into the input buffer.
This conflicted with the SIGWINCH handler that pamix registers itself and uses to refresh the ncurses window.
