### ISSUE TITLE
map <Tab> to cycle between tabs

### ISSUE THREAD

**Issue by lucas-mior** [patroclos/PAmix#48]
I've been unable to bind the Tab key in PAmix, how can it be done?
Also I haven't found any command to cycle between tabs. Can it be added?

**Comment by patroclos** [comment]
ATM there are no commands to cycle between tabs, but it can be added.
For mapping the tab key, have you tried using KEY_STAB as the keyname?

**Comment by lucas-mior** [comment]
KEY_STAB doesn't work with any commands :/

**Comment by patroclos** [comment]
Thanks for testing that out, I thought it would work, but I don't have a linux box handy RN, I'm gonna do this as soon as I get some time on my hands, probably this or next weekend

**Comment by patroclos** [comment]
Basic implementation of tab cycling exists in [feature-branch](https://github.com/patroclos/PAmix/tree/feature-tab-cycling) now.

FYI, I found the tab key gets represented by `^I` in the keybinding config.

Also, I noticed that the whole cycling experience feels a bit awkward because of the somewhat
weird ordering of tab ids.
Maybe we should reorder the internal ids to something more sensible (basically the ordering used in the default FKey bindings), but this would also mean to break existing configurations.

I think maybe the more sensible approach would be to introduce another config variable to
configure the cycle ordering.

What do you think @lucas-mior, do you have anything to add to this, since you requested the feature?

**Comment by lucas-mior** [comment]
I think the best solution would be to introduce another config variable as you suggested.
Sorry I can't help with any code since I'm not actually a programmer.
Thanks for your PAmix!
