### ISSUE TITLE
Create fedora copr repo for PAmix

### ISSUE THREAD

**Issue by anjannath** [patroclos/PAmix#56]
It'd be very helpful and make it easy to install on fedora and fedora like distros

**Comment by patroclos** [comment]
If someone wants to do this they're very welcome, but I probably won't have the time for this

**Comment by contyk** [comment]
I could help here; but why COPR when we can just add pamix to Fedora proper?

**Comment by contyk** [comment]
Anyway, here you go: https://copr.fedorainfracloud.org/coprs/psabata/pamix/

32bit ARM builds failed because the builders are misconfigured and don't have enough disk space. Hopefully that's not the arch you wanted. The rest should work. I might submit it to Fedora proper later but the review process can take a while.

**Comment by contyk** [comment]
Also submitted for Fedora proper: https://bugzilla.redhat.com/show_bug.cgi?id=1897762

**Comment by patroclos** [comment]
@contyk Awesome! Thanks for that. Good call going beyoind copr

**Comment by contyk** [comment]
Now in Rawhide. Stable repos pending.

* https://bodhi.fedoraproject.org/updates/FEDORA-2020-99c47a9286
* https://bodhi.fedoraproject.org/updates/FEDORA-2020-fb9b4debb0
